services:
  - type: web
    name: premium-digital-harvest-api
    env: node
    buildCommand: npm install --production=false && npm run build
    startCommand: node server.cjs
    envVars:
      - key: NODE_ENV
        value: production
      - key: GROQ_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: MISTRAL_API_KEY
        sync: false 