
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wgqbustrnzyyybmclwmn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndncWJ1c3Rybnp5eXlibWNsd21uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDczODIxODEsImV4cCI6MjA2Mjk1ODE4MX0.gxMGSVLrlSk32EigWWzQb_BzJ1GLZs9zBLJLemAcZuA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    storage: localStorage
  }
});
